# frozen_string_literal: true

source 'https://rubygems.org'

ruby '~> 2.7.0'

gem 'dry-system', github: 'dry-rb/dry-system'
gem "sinatra"
gem 'thin'

gem 'rom'
gem 'rom-sql'
gem 'rom-repository'
gem 'pg'

gem 'dotenv'
gem 'rake'

gem 'dry-struct'
gem 'dry-monads'

gem 'faraday'

gem 'waterdrop'
gem 'karafka'
